server:
  port: 8085
  servlet:
    context-path: /orchestrator-service

  # Frontend calls Orchestrator directly, not through API Gateway.

spring:
  application:
    name: orchestrator-service

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
